import scrapy
from selenium import webdriver
from scrapy.selector import Selector
from scrapy.utils.project import get_project_settings
import time
from ..items import Bigdata2Item
class CommentSpider(scrapy.Spider):
    name = 'comment'
    allowed_domains = ['https://www.metacritic.com']
    start_urls = ["https://www.metacritic.com/game/wii-u/elliot-quest/user-reviews",
"https://www.metacritic.com/game/pc/call-of-juarez/user-reviews",
"https://www.metacritic.com/game/game-boy-advance/hugo-the-evil-mirror/user-reviews",
"https://www.metacritic.com/game/playstation-4/rocketbirds-2-evolution/user-reviews",
"https://www.metacritic.com/game/wii/rune-factory-frontier/user-reviews",
"https://www.metacritic.com/game/pc/the-way/user-reviews",
"https://www.metacritic.com/game/pc/starcraft-ii-legacy-of-the-void/user-reviews",
"https://www.metacritic.com/game/switch/seven-pirates-h/user-reviews",
"https://www.metacritic.com/game/pc/guild-wars-2/user-reviews",
"https://www.metacritic.com/game/playstation-3/record-of-agarest-war/user-reviews",
"https://www.metacritic.com/game/pc/supremacy-four-paths-to-power/user-reviews",
"https://www.metacritic.com/game/xbox-360/narco-terror/user-reviews",
"https://www.metacritic.com/game/switch/splatoon-2/user-reviews",
"https://www.metacritic.com/game/playstation-4/nhl-18/user-reviews",
"https://www.metacritic.com/game/ds/the-legend-of-zelda-phantom-hourglass/user-reviews",
"https://www.metacritic.com/game/pc/heretic-kingdoms-the-inquisition/user-reviews",
"https://www.metacritic.com/game/playstation-2/arena-football-road-to-glory/user-reviews",
"https://www.metacritic.com/game/pc/destroyer-command/user-reviews",
"https://www.metacritic.com/game/ds/meteos-disney-magic/user-reviews",
"https://www.metacritic.com/game/nintendo-64/007-the-world-is-not-enough/user-reviews",
"https://www.metacritic.com/game/ds/bleach-the-3rd-phantom/user-reviews",
"https://www.metacritic.com/game/playstation-4/divinity-original-sin-enhanced-edition/user-reviews",
"https://www.metacritic.com/game/pc/supreme-commander-forged-alliance/user-reviews",
"https://www.metacritic.com/game/xbox/midnight-club-3-dub-edition/user-reviews",
"https://www.metacritic.com/game/playstation-4/fragments-of-him/user-reviews",
"https://www.metacritic.com/game/pc/birth-of-america/user-reviews",
"https://www.metacritic.com/game/pc/mutant-mudds/user-reviews",
"https://www.metacritic.com/game/playstation-5/mlb-the-show-21/user-reviews",
"https://www.metacritic.com/game/xbox/splashdown/user-reviews",
"https://www.metacritic.com/game/pc/lego-star-wars-the-force-awakens/user-reviews",
"https://www.metacritic.com/game/xbox-360/ssx/user-reviews",
"https://www.metacritic.com/game/playstation-5/nhl-22/user-reviews",
"https://www.metacritic.com/game/playstation-4/stardew-valley/user-reviews",
"https://www.metacritic.com/game/xbox-series-x/samurai-shodown-special-edition/user-reviews",
"https://www.metacritic.com/game/gamecube/batman-vengeance/user-reviews",
"https://www.metacritic.com/game/pc/ace-of-spades-battle-builder/user-reviews",
"https://www.metacritic.com/game/playstation-4/devil-may-cry-hd-collection/user-reviews",
"https://www.metacritic.com/game/switch/sega-ages-sonic-the-hedgehog-2/user-reviews",
"https://www.metacritic.com/game/pc/return-to-monkey-island/user-reviews",
"https://www.metacritic.com/game/playstation-3/disneypixar-brave/user-reviews",
"https://www.metacritic.com/game/pc/zoo-tycoon-2/user-reviews",
"https://www.metacritic.com/game/pc/dirt/user-reviews",
"https://www.metacritic.com/game/playstation-4/kingdom-hearts-melody-of-memory/user-reviews",
"https://www.metacritic.com/game/playstation-4/far-cry-5/user-reviews",
"https://www.metacritic.com/game/xbox-one/pro-evolution-soccer-2015/user-reviews",
"https://www.metacritic.com/game/playstation-4/deus-ex-mankind-divided/user-reviews",
"https://www.metacritic.com/game/pc/ashes-of-the-singularity/user-reviews",
"https://www.metacritic.com/game/xbox-360/risen-3-titan-lords/user-reviews",
"https://www.metacritic.com/game/xbox-360/islands-of-wakfu/user-reviews",
"https://www.metacritic.com/game/playstation-4/daylight/user-reviews",
"https://www.metacritic.com/game/3ds/pokemon-art-academy/user-reviews",
"https://www.metacritic.com/game/xbox/star-wars-jedi-knight-ii-jedi-outcast/user-reviews",
"https://www.metacritic.com/game/playstation-4/world-of-final-fantasy-maxima/user-reviews",
"https://www.metacritic.com/game/ds/ontamarama/user-reviews",
"https://www.metacritic.com/game/pc/valfaris/user-reviews",
"https://www.metacritic.com/game/xbox-one/n++/user-reviews",
"https://www.metacritic.com/game/xbox-360/crazy-machines-elements/user-reviews",
"https://www.metacritic.com/game/xbox-360/a-world-of-keflings/user-reviews",
"https://www.metacritic.com/game/pc/imperial-glory/user-reviews",
"https://www.metacritic.com/game/pc/emergency-fighters-for-life/user-reviews",
"https://www.metacritic.com/game/xbox-360/worms/user-reviews",
"https://www.metacritic.com/game/xbox-360/vandal-hearts-flames-of-judgment/user-reviews",
"https://www.metacritic.com/game/ds/the-wizard-of-oz-beyond-the-yellow-brick-road/user-reviews",
"https://www.metacritic.com/game/pc/conarium/user-reviews",
"https://www.metacritic.com/game/pc/unbound-worlds-apart/user-reviews",
"https://www.metacritic.com/game/switch/space-crew/user-reviews",
"https://www.metacritic.com/game/psp/n+/user-reviews",
"https://www.metacritic.com/game/xbox-360/arcania-gothic-4/user-reviews",
"https://www.metacritic.com/game/xbox-one/shiftlings/user-reviews",
"https://www.metacritic.com/game/pc/assetto-corsa/user-reviews",
"https://www.metacritic.com/game/playstation-4/rock-of-ages-2-bigger-boulder/user-reviews",
"https://www.metacritic.com/game/xbox-one/surviving-mars/user-reviews",
"https://www.metacritic.com/game/pc/call-of-duty-black-ops/user-reviews",
"https://www.metacritic.com/game/pc/the-walking-dead-michonne---episode-2-give-no-shelter/user-reviews",
"https://www.metacritic.com/game/playstation-4/wrc-5/user-reviews",
"https://www.metacritic.com/game/playstation-4/gravity-rush-remastered/user-reviews",
"https://www.metacritic.com/game/playstation-4/statik/user-reviews",
"https://www.metacritic.com/game/playstation-2/silent-hill-4-the-room/user-reviews",
"https://www.metacritic.com/game/playstation-4/fluster-cluck/user-reviews",
"https://www.metacritic.com/game/xbox/silent-hill-2-restless-dreams/user-reviews",
"https://www.metacritic.com/game/xbox/aquaman-battle-for-atlantis/user-reviews",
"https://www.metacritic.com/game/playstation-4/zen-pinball-2-balls-of-glory/user-reviews",
"https://www.metacritic.com/game/playstation-vita/lego-the-lord-of-the-rings/user-reviews",
"https://www.metacritic.com/game/xbox-360/beautiful-katamari/user-reviews",
"https://www.metacritic.com/game/pc/atlantis-quest/user-reviews",
"https://www.metacritic.com/game/gamecube/nba-courtside-2002/user-reviews",
"https://www.metacritic.com/game/gamecube/madden-nfl-2005/user-reviews",
"https://www.metacritic.com/game/pc/shadowgrounds/user-reviews",
"https://www.metacritic.com/game/psp/mana-khemia-student-alliance/user-reviews",
"https://www.metacritic.com/game/ds/art-style-pictobits/user-reviews",
"https://www.metacritic.com/game/pc/art-of-rally/user-reviews",
"https://www.metacritic.com/game/playstation-2/monster-rancher-4/user-reviews",
"https://www.metacritic.com/game/pc/volume/user-reviews",
"https://www.metacritic.com/game/xbox-360/tiger-woods-pga-tour-07/user-reviews",
"https://www.metacritic.com/game/gamecube/mc-groovz-dance-craze/user-reviews",
"https://www.metacritic.com/game/playstation-2/star-wars-starfighter/user-reviews",
"https://www.metacritic.com/game/game-boy-advance/dragon-ball-z-the-legacy-of-goku-ii/user-reviews",
"https://www.metacritic.com/game/ds/pokemon-white-version-2/user-reviews",
"https://www.metacritic.com/game/pc/timelie/user-reviews",
"https://www.metacritic.com/game/3ds/ikachan/user-reviews",
"https://www.metacritic.com/game/xbox-series-x/shredders/user-reviews",
"https://www.metacritic.com/game/xbox-360/section-8/user-reviews",
"https://www.metacritic.com/game/playstation-5/far-cry-6/user-reviews",
"https://www.metacritic.com/game/switch/amnesia-collection/user-reviews",
"https://www.metacritic.com/game/playstation-4/the-quiet-man/user-reviews",
"https://www.metacritic.com/game/playstation-4/darius-cozmic-collection-arcade/user-reviews",
"https://www.metacritic.com/game/switch/infinite-minigolf/user-reviews",
"https://www.metacritic.com/game/xbox-360/call-of-duty-black-ops---annihilation/user-reviews",
"https://www.metacritic.com/game/xbox-360/battlestations-pacific/user-reviews",
"https://www.metacritic.com/game/switch/yooka-laylee-and-the-impossible-lair/user-reviews",
"https://www.metacritic.com/game/xbox-one/rise-shine/user-reviews",
"https://www.metacritic.com/game/playstation-vita/tokyo-twilight-ghost-hunters/user-reviews",
"https://www.metacritic.com/game/pc/grey-goo/user-reviews",
"https://www.metacritic.com/game/playstation-2/casper-spirit-dimensions/user-reviews",
"https://www.metacritic.com/game/pc/nba-live-2003/user-reviews",
"https://www.metacritic.com/game/playstation-4/nba-2k15/user-reviews",
"https://www.metacritic.com/game/pc/pagan-online/user-reviews",
"https://www.metacritic.com/game/playstation-3/dark-souls/user-reviews",
"https://www.metacritic.com/game/xbox-one/monster-hunter-world---iceborne/user-reviews",
"https://www.metacritic.com/game/xbox-one/tropico-6/user-reviews",
"https://www.metacritic.com/game/pc/line-of-sight-vietnam/user-reviews",
"https://www.metacritic.com/game/pc/medieval-total-war---viking-invasion/user-reviews",
"https://www.metacritic.com/game/pc/action-henk/user-reviews",
"https://www.metacritic.com/game/xbox/whacked!/user-reviews",
"https://www.metacritic.com/game/pc/star-trek-voyager-elite-force-expansion-pack/user-reviews",
"https://www.metacritic.com/game/pc/tetrobot-and-co/user-reviews",
"https://www.metacritic.com/game/pc/war-for-the-overworld/user-reviews",
"https://www.metacritic.com/game/gamecube/the-sims/user-reviews",
"https://www.metacritic.com/game/gamecube/hitman-2-silent-assassin/user-reviews",
"https://www.metacritic.com/game/playstation-3/create/user-reviews",
"https://www.metacritic.com/game/pc/neo-cab/user-reviews",
"https://www.metacritic.com/game/playstation-4/mulaka/user-reviews",
"https://www.metacritic.com/game/pc/watch-dogs-2/user-reviews",
"https://www.metacritic.com/game/xbox-360/the-spiderwick-chronicles/user-reviews",
"https://www.metacritic.com/game/ds/deep-labyrinth/user-reviews",
"https://www.metacritic.com/game/playstation-2/goldeneye-rogue-agent/user-reviews",
"https://www.metacritic.com/game/pc/universal-combat/user-reviews",
"https://www.metacritic.com/game/wii/racquet-sports/user-reviews",
"https://www.metacritic.com/game/wii/tetris-party-deluxe/user-reviews",
"https://www.metacritic.com/game/pc/total-war-warhammer-ii---curse-of-the-vampire-coast/user-reviews",
"https://www.metacritic.com/game/pc/the-walking-dead-season-two---a-telltale-games-series/user-reviews",
"https://www.metacritic.com/game/pc/the-crew/user-reviews",
"https://www.metacritic.com/game/playstation-2/uefa-champions-league-2006-2007/user-reviews",
"https://www.metacritic.com/game/pc/nancy-drew-danger-on-deception-island/user-reviews",
"https://www.metacritic.com/game/pc/ryse-son-of-rome/user-reviews",
"https://www.metacritic.com/game/wii/bittrip-fate/user-reviews",
"https://www.metacritic.com/game/xbox-360/street-fighter-x-tekken/user-reviews",
"https://www.metacritic.com/game/pc/spacechem/user-reviews",
"https://www.metacritic.com/game/xbox-360/crystal-defenders/user-reviews",
"https://www.metacritic.com/game/pc/tannenberg/user-reviews",
"https://www.metacritic.com/game/xbox-360/tetris-evolution/user-reviews",
"https://www.metacritic.com/game/playstation-4/white-day-a-labyrinth-named-school/user-reviews",
"https://www.metacritic.com/game/game-boy-advance/pokemon-pinball-ruby-sapphire/user-reviews",
"https://www.metacritic.com/game/playstation-4/necromunda-underhive-wars/user-reviews",
"https://www.metacritic.com/game/xbox-one/fragments-of-him/user-reviews",
"https://www.metacritic.com/game/playstation-4/resident-evil-3/user-reviews",
"https://www.metacritic.com/game/pc/sacred-underworld/user-reviews",
"https://www.metacritic.com/game/pc/morbid-the-seven-acolytes/user-reviews",
"https://www.metacritic.com/game/xbox-one/fortified/user-reviews",
"https://www.metacritic.com/game/playstation-3/scarygirl/user-reviews",
"https://www.metacritic.com/game/wii/simanimals/user-reviews",
"https://www.metacritic.com/game/playstation-2/the-simpsons-skateboarding/user-reviews",
"https://www.metacritic.com/game/wii/cave-story/user-reviews",
"https://www.metacritic.com/game/playstation/parasite-eve-ii/user-reviews",
"https://www.metacritic.com/game/pc/doom/user-reviews",
"https://www.metacritic.com/game/gamecube/mario-power-tennis/user-reviews",
"https://www.metacritic.com/game/pc/the-suicide-of-rachel-foster/user-reviews",
"https://www.metacritic.com/game/ds/bubble-bobble-double-shot/user-reviews",
"https://www.metacritic.com/game/ds/zendoku/user-reviews",
"https://www.metacritic.com/game/pc/crimecraft/user-reviews",
"https://www.metacritic.com/game/playstation-2/nhl-06/user-reviews",
"https://www.metacritic.com/game/playstation-3/3-on-3-nhl-arcade/user-reviews",
"https://www.metacritic.com/game/playstation-2/monster-rancher-4/user-reviews",
"https://www.metacritic.com/game/pc/call-of-duty-black-ops-cold-war/user-reviews",
"https://www.metacritic.com/game/xbox-360/madden-nfl-12/user-reviews",
"https://www.metacritic.com/game/playstation-4/mlb-the-show-16/user-reviews",
"https://www.metacritic.com/game/pc/daemonica/user-reviews",
"https://www.metacritic.com/game/playstation-5/devil-may-cry-5-special-edition/user-reviews",
"https://www.metacritic.com/game/switch/the-lego-movie-2-videogame/user-reviews",
"https://www.metacritic.com/game/switch/mario-+-rabbids-kingdom-battle/user-reviews",
"https://www.metacritic.com/game/xbox-360/rayman-legends/user-reviews",
"https://www.metacritic.com/game/wii/big-beach-sports/user-reviews",
"https://www.metacritic.com/game/game-boy-advance/banjo-pilot/user-reviews",
"https://www.metacritic.com/game/switch/going-under/user-reviews",
"https://www.metacritic.com/game/xbox-360/cloudy-with-a-chance-of-meatballs/user-reviews",
"https://www.metacritic.com/game/wii/resident-evil-the-darkside-chronicles/user-reviews",
"https://www.metacritic.com/game/pc/dreadout/user-reviews",
"https://www.metacritic.com/game/wii/jumpstart-escape-from-adventure-island/user-reviews",
"https://www.metacritic.com/game/xbox-360/sonic-the-hedgehog-4-episode-ii/user-reviews",
"https://www.metacritic.com/game/game-boy-advance/castlevania-circle-of-the-moon/user-reviews",
"https://www.metacritic.com/game/xbox-360/dishonored-the-brigmore-witches/user-reviews",
"https://www.metacritic.com/game/playstation-2/aeon-flux/user-reviews",
"https://www.metacritic.com/game/gamecube/resident-evil-2/user-reviews",
"https://www.metacritic.com/game/playstation-vita/metal-gear-solid-hd-collection/user-reviews",
"https://www.metacritic.com/game/xbox-360/street-fighter-iii-third-strike-online-edition/user-reviews",
"https://www.metacritic.com/game/ds/lego-battles-ninjago/user-reviews",
"https://www.metacritic.com/game/pc/citizen-sleeper/user-reviews",
"https://www.metacritic.com/game/playstation-4/street-fighter-v-champion-edition/user-reviews",
"https://www.metacritic.com/game/xbox-360/earthworm-jim-hd/user-reviews",
"https://www.metacritic.com/game/wii-u/f1-race-stars-powered-up-edition/user-reviews",
"https://www.metacritic.com/game/3ds/radiohammer/user-reviews",
"https://www.metacritic.com/game/pc/mechwarrior-5-mercenaries/user-reviews",
"https://www.metacritic.com/game/pc/prey-2006/user-reviews",
"https://www.metacritic.com/game/gamecube/outlaw-golf/user-reviews",
"https://www.metacritic.com/game/pc/the-walking-dead-a-telltale-games-series/user-reviews",
"https://www.metacritic.com/game/playstation-4/pinball-fx2-vr/user-reviews",
"https://www.metacritic.com/game/playstation-3/littlebigplanet/user-reviews",
"https://www.metacritic.com/game/playstation-4/borderlands-the-handsome-collection/user-reviews",
"https://www.metacritic.com/game/xbox-one/twin-mirror/user-reviews",
"https://www.metacritic.com/game/playstation-3/shaun-white-snowboarding/user-reviews",
"https://www.metacritic.com/game/3ds/the-legend-of-legacy/user-reviews",
"https://www.metacritic.com/game/pc/neverwinter-nights-shadows-of-undrentide/user-reviews",
"https://www.metacritic.com/game/pc/lego-star-wars-the-skywalker-saga/user-reviews",
"https://www.metacritic.com/game/playstation-2/espn-nfl-primetime-2002/user-reviews",
"https://www.metacritic.com/game/nintendo-64/dr-mario-64/user-reviews",
"https://www.metacritic.com/game/pc/the-elder-scrolls-iii-tribunal/user-reviews",
"https://www.metacritic.com/game/psp/nba-ballers-rebound/user-reviews",
"https://www.metacritic.com/game/xbox-360/left-4-dead-2-the-passing/user-reviews",
"https://www.metacritic.com/game/wii/the-simpsons-game/user-reviews",
"https://www.metacritic.com/game/playstation-4/the-elder-scrolls-v-skyrim-special-edition/user-reviews",
"https://www.metacritic.com/game/wii/muscle-march/user-reviews",
"https://www.metacritic.com/game/playstation-4/nba-live-15/user-reviews",
"https://www.metacritic.com/game/switch/horace/user-reviews",
"https://www.metacritic.com/game/ds/puzzle-kingdoms/user-reviews",
"https://www.metacritic.com/game/gamecube/donkey-kong-jungle-beat/user-reviews",
"https://www.metacritic.com/game/playstation-4/i-am-setsuna/user-reviews",
"https://www.metacritic.com/game/switch/sega-ages-g-loc-air-battle/user-reviews",
"https://www.metacritic.com/game/xbox-one/forza-horizon-4-lego-speed-champions/user-reviews",
"https://www.metacritic.com/game/pc/saints-row/user-reviews",
"https://www.metacritic.com/game/3ds/story-of-seasons-trio-of-towns/user-reviews",
"https://www.metacritic.com/game/playstation-2/motogp-4/user-reviews",
"https://www.metacritic.com/game/playstation-3/time-crisis-4/user-reviews",
"https://www.metacritic.com/game/xbox-360/kinect-star-wars/user-reviews",
"https://www.metacritic.com/game/ds/transformers-war-for-cybertron---autobots/user-reviews",
"https://www.metacritic.com/game/switch/dragon-quest/user-reviews",
"https://www.metacritic.com/game/pc/dark-souls-ii-scholar-of-the-first-sin/user-reviews",
"https://www.metacritic.com/game/playstation/triple-play-baseball/user-reviews",
"https://www.metacritic.com/game/pc/ghost-10/user-reviews",
"https://www.metacritic.com/game/dreamcast/tennis-2k2/user-reviews",
"https://www.metacritic.com/game/pc/football-manager-2010/user-reviews",
"https://www.metacritic.com/game/playstation-2/pro-race-driver/user-reviews",
"https://www.metacritic.com/game/playstation-4/control/user-reviews",
"https://www.metacritic.com/game/switch/xenoblade-chronicles-definitive-edition/user-reviews",
"https://www.metacritic.com/game/pc/call-of-duty-modern-warfare-2/user-reviews",
"https://www.metacritic.com/game/pc/once-upon-a-knight/user-reviews",
"https://www.metacritic.com/game/playstation-4/fairy-fencer-f-advent-dark-force/user-reviews",
"https://www.metacritic.com/game/nintendo-64/star-wars-rogue-squadron/user-reviews",
"https://www.metacritic.com/game/playstation/c-12-final-resistance/user-reviews",
"https://www.metacritic.com/game/switch/unravel-two/user-reviews",
"https://www.metacritic.com/game/xbox-one/dishonored-definitive-edition/user-reviews",
"https://www.metacritic.com/game/xbox-one/ride-4/user-reviews",
"https://www.metacritic.com/game/pc/fallout-new-vegas---honest-hearts/user-reviews",
"https://www.metacritic.com/game/playstation-4/daymare-1998/user-reviews",
"https://www.metacritic.com/game/ds/pokemon-ranger-guardian-signs/user-reviews",
"https://www.metacritic.com/game/switch/thief-of-thieves-season-one/user-reviews",
"https://www.metacritic.com/game/playstation-2/herdy-gerdy/user-reviews",
"https://www.metacritic.com/game/playstation-2/delta-force-black-hawk-down/user-reviews",
"https://www.metacritic.com/game/switch/dragon-ball-xenoverse-2/user-reviews",
"https://www.metacritic.com/game/playstation-4/overpass/user-reviews",
"https://www.metacritic.com/game/pc/football-mogul-2007/user-reviews",
"https://www.metacritic.com/game/pc/fifa-15/user-reviews",
"https://www.metacritic.com/game/xbox-one/remothered-broken-porcelain/user-reviews",
"https://www.metacritic.com/game/pc/divinity-original-sin-ii/user-reviews",
"https://www.metacritic.com/game/pc/the-elder-scrolls-iii-morrowind/user-reviews",
"https://www.metacritic.com/game/pc/the-x-files-game/user-reviews",
"https://www.metacritic.com/game/switch/taiko-no-tatsujin-rhythm-festival/user-reviews",
"https://www.metacritic.com/game/xbox-one/game-of-thrones-episode-three---the-sword-in-the-darkness/user-reviews",
"https://www.metacritic.com/game/xbox-360/paperboy/user-reviews",
"https://www.metacritic.com/game/xbox-one/code-vein/user-reviews",
"https://www.metacritic.com/game/ds/flash-focus-vision-training-in-minutes-a-day/user-reviews",
"https://www.metacritic.com/game/switch/world-of-goo/user-reviews",
"https://www.metacritic.com/game/game-boy-advance/mech-platoon/user-reviews",
"https://www.metacritic.com/game/playstation-4/oxenfree/user-reviews",
"https://www.metacritic.com/game/pc/batman-the-enemy-within---episode-1-the-enigma/user-reviews",
"https://www.metacritic.com/game/pc/etherlords/user-reviews",
"https://www.metacritic.com/game/playstation-4/conan-exiles/user-reviews",
"https://www.metacritic.com/game/pc/sanctum-2/user-reviews",
"https://www.metacritic.com/game/gamecube/i-ninja/user-reviews",
"https://www.metacritic.com/game/pc/cultist-simulator/user-reviews",
"https://www.metacritic.com/game/xbox-one/steep/user-reviews",
"https://www.metacritic.com/game/playstation-4/ultimate-marvel-vs-capcom-3/user-reviews",
"https://www.metacritic.com/game/xbox/wwe-wrestlemania-21/user-reviews",
"https://www.metacritic.com/game/pc/never-alone/user-reviews",
"https://www.metacritic.com/game/wii-u/year-walk/user-reviews",
"https://www.metacritic.com/game/xbox-one/factotum-90/user-reviews",
"https://www.metacritic.com/game/pc/fury/user-reviews",
"https://www.metacritic.com/game/xbox-360/sonic-all-stars-racing-transformed/user-reviews",
"https://www.metacritic.com/game/xbox-360/halo-3/user-reviews",
"https://www.metacritic.com/game/switch/paper-mario-the-origami-king/user-reviews",
"https://www.metacritic.com/game/playstation-4/the-last-guardian/user-reviews",
"https://www.metacritic.com/game/psp/final-fantasy/user-reviews",
"https://www.metacritic.com/game/xbox-one/wrc-9-fia-world-rally-championship/user-reviews",
"https://www.metacritic.com/game/pc/moons-of-madness/user-reviews",
"https://www.metacritic.com/game/xbox/the-spongebob-squarepants-movie/user-reviews",
"https://www.metacritic.com/game/playstation-2/the-dukes-of-hazzard-return-of-the-general-lee/user-reviews",
"https://www.metacritic.com/game/pc/total-war-rome-ii---caesar-in-gaul/user-reviews",
"https://www.metacritic.com/game/playstation-3/blacksite-area-51/user-reviews",
"https://www.metacritic.com/game/playstation-2/fullmetal-alchemist-2-curse-of-the-crimson-elixir/user-reviews",
"https://www.metacritic.com/game/playstation-2/taito-legends/user-reviews",
"https://www.metacritic.com/game/xbox/genma-onimusha/user-reviews",
"https://www.metacritic.com/game/xbox-360/the-walking-dead-season-two-episode-4---amid-the-ruins/user-reviews",
"https://www.metacritic.com/game/playstation-3/lego-rock-band/user-reviews",
"https://www.metacritic.com/game/wii/resident-evil-archives-resident-evil-zero/user-reviews",
"https://www.metacritic.com/game/playstation-2/nascar-dirt-to-daytona/user-reviews",
"https://www.metacritic.com/game/switch/brothers-a-tale-of-two-sons/user-reviews",
"https://www.metacritic.com/game/pc/unreal-tournament-iii/user-reviews",
"https://www.metacritic.com/game/pc/broken-age/user-reviews",
"https://www.metacritic.com/game/pc/time-machine-vr/user-reviews",
"https://www.metacritic.com/game/playstation-2/alias/user-reviews",
"https://www.metacritic.com/game/pc/gloomhaven/user-reviews",
"https://www.metacritic.com/game/xbox-one/resident-evil-revelations-2---episode-3-judgment/user-reviews",
"https://www.metacritic.com/game/xbox-360/naughty-bear-panic-in-paradise/user-reviews",
"https://www.metacritic.com/game/pc/starcraft-ii-legacy-of-the-void/user-reviews",
"https://www.metacritic.com/game/gamecube/geist/user-reviews",
"https://www.metacritic.com/game/xbox-360/plants-vs-zombies/user-reviews",
"https://www.metacritic.com/game/psp/prince-of-persia-revelations/user-reviews",
"https://www.metacritic.com/game/xbox/turok-evolution/user-reviews",
"https://www.metacritic.com/game/wii-u/tekken-tag-tournament-2-wii-u-edition/user-reviews",
"https://www.metacritic.com/game/playstation-2/brothers-in-arms-road-to-hill-30/user-reviews",
"https://www.metacritic.com/game/playstation-3/dead-space-3/user-reviews",
"https://www.metacritic.com/game/xbox/apex/user-reviews",
"https://www.metacritic.com/game/pc/trapped-dead/user-reviews",
"https://www.metacritic.com/game/playstation-4/minecraft-story-mode---episode-4-a-block-and-a-hard-place/user-reviews",
"https://www.metacritic.com/game/xbox/tiger-woods-pga-tour-07/user-reviews",
"https://www.metacritic.com/game/xbox-one/darksiders-genesis/user-reviews",
"https://www.metacritic.com/game/xbox-360/the-outfit/user-reviews",
"https://www.metacritic.com/game/playstation-3/dead-space/user-reviews",
"https://www.metacritic.com/game/switch/catherine-full-body/user-reviews",
"https://www.metacritic.com/game/switch/the-escapists-complete-edition/user-reviews",
"https://www.metacritic.com/game/playstation-2/psychonauts/user-reviews",
"https://www.metacritic.com/game/switch/the-coma-recut/user-reviews",
"https://www.metacritic.com/game/playstation-2/mercenaries/user-reviews",
"https://www.metacritic.com/game/3ds/kid-icarus-uprising/user-reviews",
"https://www.metacritic.com/game/pc/chinatown-detective-agency/user-reviews",
"https://www.metacritic.com/game/gamecube/one-piece-grand-battle/user-reviews",
"https://www.metacritic.com/game/xbox-360/la-noire-nicholson-electroplating-disaster/user-reviews",
"https://www.metacritic.com/game/xbox/dreamfall-the-longest-journey/user-reviews",
"https://www.metacritic.com/game/switch/syberia/user-reviews",
"https://www.metacritic.com/game/pc/horizons-empire-of-istaria/user-reviews",
"https://www.metacritic.com/game/playstation-2/romance-of-the-three-kingdoms-vii/user-reviews",
"https://www.metacritic.com/game/xbox-one/plants-vs-zombies-garden-warfare-2/user-reviews",
"https://www.metacritic.com/game/playstation/arc-the-lad-collection/user-reviews",
"https://www.metacritic.com/game/xbox-360/bust-a-move-live!/user-reviews",
"https://www.metacritic.com/game/xbox-360/sleeping-dogs/user-reviews",
"https://www.metacritic.com/game/psp/coded-arms-contagion/user-reviews",
"https://www.metacritic.com/game/ds/brain-challenge/user-reviews",
"https://www.metacritic.com/game/playstation-3/gi-joe-the-rise-of-cobra/user-reviews",
"https://www.metacritic.com/game/wii-u/how-to-survive/user-reviews",
"https://www.metacritic.com/game/xbox-360/cellfactor-psychokinetic-wars/user-reviews",
"https://www.metacritic.com/game/xbox-series-x/nhl-22/user-reviews",
"https://www.metacritic.com/game/switch/blaster-master-zero-iii/user-reviews",
"https://www.metacritic.com/game/xbox-one/fragments-of-him/user-reviews",
"https://www.metacritic.com/game/playstation-5/balan-wonderworld/user-reviews",
"https://www.metacritic.com/game/pc/dark-age-of-camelot-trials-of-atlantis/user-reviews",
"https://www.metacritic.com/game/playstation-5/romancing-saga-minstrel-song-remastered/user-reviews",
"https://www.metacritic.com/game/playstation-3/ncaa-football-12/user-reviews",
"https://www.metacritic.com/game/xbox/midnight-club-ii/user-reviews",
"https://www.metacritic.com/game/pc/b-17-flying-fortress-the-mighty-8th!/user-reviews",
"https://www.metacritic.com/game/switch/darksiders-warmastered-edition/user-reviews",
"https://www.metacritic.com/game/switch/fitness-boxing-2-rhythm-exercise/user-reviews",
"https://www.metacritic.com/game/playstation-4/minit/user-reviews",
"https://www.metacritic.com/game/pc/cornerstone-the-song-of-tyrim/user-reviews",
"https://www.metacritic.com/game/wii/adventure-island-the-beginning/user-reviews",
"https://www.metacritic.com/game/ds/disneypixar-wall-e/user-reviews",
"https://www.metacritic.com/game/pc/hellgate-london/user-reviews",
"https://www.metacritic.com/game/playstation-4/galgun-double-peace/user-reviews",
"https://www.metacritic.com/game/pc/risk-of-rain/user-reviews",
"https://www.metacritic.com/game/xbox/destroy-all-humans!-2/user-reviews",
"https://www.metacritic.com/game/pc/arena-wars/user-reviews",
"https://www.metacritic.com/game/xbox-one/avicii-invector/user-reviews",
"https://www.metacritic.com/game/pc/inmomentum/user-reviews",
"https://www.metacritic.com/game/xbox/all-star-baseball-2005/user-reviews",
"https://www.metacritic.com/game/playstation-4/spiritfarer/user-reviews",
"https://www.metacritic.com/game/pc/a-normal-lost-phone/user-reviews",
"https://www.metacritic.com/game/xbox/harry-potter-and-the-prisoner-of-azkaban/user-reviews",
"https://www.metacritic.com/game/pc/nba-live-06/user-reviews",
"https://www.metacritic.com/game/xbox-series-x/road-96/user-reviews",
"https://www.metacritic.com/game/playstation-4/overcooked!-2/user-reviews",
"https://www.metacritic.com/game/gamecube/4x4-evo-2/user-reviews",
"https://www.metacritic.com/game/xbox-360/nascar-the-game-inside-line/user-reviews",
"https://www.metacritic.com/game/pc/cosmic-star-heroine/user-reviews",
"https://www.metacritic.com/game/wii/ea-sports-active-2/user-reviews",
"https://www.metacritic.com/game/switch/synthetik-ultimate/user-reviews",
"https://www.metacritic.com/game/xbox-one/fe/user-reviews",
"https://www.metacritic.com/game/pc/night-watch/user-reviews",
"https://www.metacritic.com/game/3ds/conception-ii-children-of-the-seven-stars/user-reviews",
"https://www.metacritic.com/game/playstation-2/reservoir-dogs/user-reviews",
"https://www.metacritic.com/game/pc/neverwinter-nights/user-reviews",
"https://www.metacritic.com/game/xbox-series-x/override-2-super-mech-league/user-reviews",
"https://www.metacritic.com/game/switch/castle-of-heart/user-reviews",
"https://www.metacritic.com/game/playstation-2/chessmaster/user-reviews",
"https://www.metacritic.com/game/playstation-3/castlevania-harmony-of-despair/user-reviews",
"https://www.metacritic.com/game/playstation-4/mega-man-11/user-reviews",
"https://www.metacritic.com/game/pc/csi-crime-scene-investigation-dark-motives/user-reviews",
"https://www.metacritic.com/game/pc/need-for-speed-the-run/user-reviews",
"https://www.metacritic.com/game/playstation-3/fifa-soccer-11/user-reviews",
"https://www.metacritic.com/game/xbox-series-x/far-cry-6/user-reviews",
"https://www.metacritic.com/game/ds/fifa-07-soccer/user-reviews",
"https://www.metacritic.com/game/pc/crusader-kings-ii/user-reviews",
"https://www.metacritic.com/game/pc/el-matador/user-reviews",
"https://www.metacritic.com/game/game-boy-advance/metal-slug-advance/user-reviews",
"https://www.metacritic.com/game/xbox-one/superhot/user-reviews",
"https://www.metacritic.com/game/switch/cooking-mama-cookstar/user-reviews",
"https://www.metacritic.com/game/playstation-3/metal-gear-solid-4-guns-of-the-patriots/user-reviews",
"https://www.metacritic.com/game/playstation-4/megaton-rainfall/user-reviews",
"https://www.metacritic.com/game/gamecube/charlie-and-the-chocolate-factory/user-reviews",
"https://www.metacritic.com/game/playstation-4/the-metronomicon-slay-the-dance-floor/user-reviews",
"https://www.metacritic.com/game/playstation-3/ncaa-football-14/user-reviews",
"https://www.metacritic.com/game/pc/impact-winter/user-reviews",
"https://www.metacritic.com/game/playstation-4/shantae-and-the-seven-sirens/user-reviews",
"https://www.metacritic.com/game/playstation/monsters-inc-scream-team/user-reviews",
"https://www.metacritic.com/game/playstation-4/planetside-2/user-reviews",
"https://www.metacritic.com/game/pc/ufo-afterlight/user-reviews",
"https://www.metacritic.com/game/switch/in-other-waters/user-reviews",
"https://www.metacritic.com/game/playstation-4/super-rude-bear-resurrection/user-reviews",
"https://www.metacritic.com/game/pc/worldshift/user-reviews",
"https://www.metacritic.com/game/playstation-2/mlb-07-the-show/user-reviews",
"https://www.metacritic.com/game/pc/ripd-the-game/user-reviews",
"https://www.metacritic.com/game/ds/bionicle-heroes/user-reviews",
"https://www.metacritic.com/game/pc/kickbeat-steam-edition/user-reviews",
"https://www.metacritic.com/game/psp/the-3rd-birthday/user-reviews",
"https://www.metacritic.com/game/playstation-2/mobile-suit-gundam-federation-vs-zeon/user-reviews",
"https://www.metacritic.com/game/pc/codename-panzers-phase-one/user-reviews",
"https://www.metacritic.com/game/pc/vaporum/user-reviews",
"https://www.metacritic.com/game/playstation-3/thomas-was-alone/user-reviews",
"https://www.metacritic.com/game/playstation-4/rigs-mechanized-combat-league/user-reviews",
"https://www.metacritic.com/game/wii-u/the-amazing-spider-man/user-reviews",
"https://www.metacritic.com/game/playstation-vita/lumines-electronic-symphony/user-reviews",
"https://www.metacritic.com/game/switch/city-of-brass/user-reviews",
"https://www.metacritic.com/game/playstation-4/dead-rising-triple-pack/user-reviews",
"https://www.metacritic.com/game/xbox-360/baja-edge-of-control/user-reviews",
"https://www.metacritic.com/game/dreamcast/sega-gt/user-reviews",
"https://www.metacritic.com/game/playstation-3/batman-arkham-origins-blackgate---deluxe-edition/user-reviews",
"https://www.metacritic.com/game/playstation-2/magna-carta-tears-of-blood/user-reviews",
"https://www.metacritic.com/game/game-boy-advance/street-jam-basketball/user-reviews",
"https://www.metacritic.com/game/pc/icewind-dale-ii/user-reviews",
"https://www.metacritic.com/game/playstation-2/lego-soccer-mania/user-reviews",
"https://www.metacritic.com/game/game-boy-advance/the-revenge-of-shinobi/user-reviews",
"https://www.metacritic.com/game/ds/spore-creatures/user-reviews",
"https://www.metacritic.com/game/ds/advance-wars-dual-strike/user-reviews",
"https://www.metacritic.com/game/pc/spider-man-3/user-reviews",
"https://www.metacritic.com/game/playstation-4/regalia-of-men-and-monarchs---royal-edition/user-reviews",
"https://www.metacritic.com/game/playstation-4/dead-cells/user-reviews",
"https://www.metacritic.com/game/psp/mana-khemia-student-alliance/user-reviews",
"https://www.metacritic.com/game/switch/pokemon-unite/user-reviews",
"https://www.metacritic.com/game/pc/zombeer/user-reviews",
"https://www.metacritic.com/game/playstation-5/warhammer-chaosbane/user-reviews",
"https://www.metacritic.com/game/pc/rive/user-reviews",
"https://www.metacritic.com/game/xbox-one/dakar-18/user-reviews",
"https://www.metacritic.com/game/psp/socom-us-navy-seals-fireteam-bravo-3/user-reviews",
"https://www.metacritic.com/game/playstation-4/gran-turismo-sport/user-reviews",
"https://www.metacritic.com/game/xbox-360/fifa-07-soccer/user-reviews",
"https://www.metacritic.com/game/pc/nether/user-reviews",
"https://www.metacritic.com/game/playstation-vita/lego-batman-2-dc-super-heroes/user-reviews",
"https://www.metacritic.com/game/xbox/tiger-woods-pga-tour-2003/user-reviews",
"https://www.metacritic.com/game/pc/ladykiller-in-a-bind/user-reviews",
"https://www.metacritic.com/game/playstation-2/fantavision/user-reviews",
"https://www.metacritic.com/game/playstation-5/deliver-us-mars/user-reviews",
"https://www.metacritic.com/game/switch/nexomon-extinction/user-reviews",
"https://www.metacritic.com/game/playstation-4/bound/user-reviews",
"https://www.metacritic.com/game/ds/heroes-of-mana/user-reviews",
"https://www.metacritic.com/game/xbox-one/guns-gore-cannoli/user-reviews",
"https://www.metacritic.com/game/xbox-360/disney-ducktales-remastered/user-reviews",
"https://www.metacritic.com/game/playstation-3/nhl-13/user-reviews",
"https://www.metacritic.com/game/playstation-2/capcom-vs-snk-2-mark-of-the-millennium-2001/user-reviews",
"https://www.metacritic.com/game/psp/fifa-world-cup-germany-2006/user-reviews",
"https://www.metacritic.com/game/pc/max-payne-3/user-reviews",
"https://www.metacritic.com/game/playstation-4/hitman---episode-3-marrakesh/user-reviews",
"https://www.metacritic.com/game/xbox-one/my-time-at-portia/user-reviews",
"https://www.metacritic.com/game/playstation-5/the-last-of-us-part-i/user-reviews",
"https://www.metacritic.com/game/playstation-2/xiii/user-reviews",
"https://www.metacritic.com/game/gamecube/ncaa-football-2003/user-reviews",
"https://www.metacritic.com/game/playstation-4/the-dark-crystal-age-of-resistance-tactics/user-reviews",
"https://www.metacritic.com/game/pc/advent-rising/user-reviews",
"https://www.metacritic.com/game/pc/metal-gear-solid-v-ground-zeroes/user-reviews",
"https://www.metacritic.com/game/pc/inscryption/user-reviews",
"https://www.metacritic.com/game/playstation-2/the-legend-of-spyro-a-new-beginning/user-reviews",
"https://www.metacritic.com/game/playstation-4/kandagawa-jet-girls/user-reviews",
"https://www.metacritic.com/game/pc/severed-steel/user-reviews",
"https://www.metacritic.com/game/xbox-360/how-to-survive/user-reviews",
"https://www.metacritic.com/game/playstation-4/little-red-lie/user-reviews",
"https://www.metacritic.com/game/playstation-5/gigabash/user-reviews",
"https://www.metacritic.com/game/playstation-2/space-channel-5-special-edition/user-reviews",
"https://www.metacritic.com/game/psp/invizimals/user-reviews",
"https://www.metacritic.com/game/pc/fallout-3-the-pitt/user-reviews",
"https://www.metacritic.com/game/switch/what-the-golf/user-reviews",
"https://www.metacritic.com/game/xbox-one/asterix-obelix-xxl-3-the-crystal-menhir/user-reviews",
"https://www.metacritic.com/game/playstation-5/anno-mutationem/user-reviews",
"https://www.metacritic.com/game/playstation-4/disco-elysium-the-final-cut/user-reviews",
"https://www.metacritic.com/game/playstation-4/efootball-pes-2020/user-reviews",
"https://www.metacritic.com/game/xbox-one/destiny-2-forsaken/user-reviews",
"https://www.metacritic.com/game/playstation-2/pirates-of-the-caribbean-the-legend-of-jack-sparrow/user-reviews",
"https://www.metacritic.com/game/psp/army-of-two-the-40th-day/user-reviews",
"https://www.metacritic.com/game/xbox-series-x/alan-wake-remastered/user-reviews",
"https://www.metacritic.com/game/playstation-2/evergrace/user-reviews",
"https://www.metacritic.com/game/pc/dreamkiller/user-reviews",
"https://www.metacritic.com/game/pc/raven-squad-operation-hidden-dagger/user-reviews",
"https://www.metacritic.com/game/pc/deep-black-reloaded/user-reviews",
"https://www.metacritic.com/game/game-boy-advance/need-for-speed-underground/user-reviews",
"https://www.metacritic.com/game/psp/taito-legends-power-up/user-reviews"]

    def parse(self, response):
        settings = get_project_settings()
        driver_path = settings['CHROME_DRIVER_PATH']
        options= webdriver.ChromeOptions()
        options.add_argument('headless')
        options.add_argument('disable-popup-blocking')
        options.add_argument('--log-level=1')
        driver = webdriver.Chrome(driver_path, options=options)
        driver.get(response.url)
        time.sleep(3)
        #Duyệt toàn bộ trang web
        while True:
            g_url = driver.current_url
            g_reviewer_name = "NA"
            g_comment_date = "NA"
            # g_reviever_helpfulvote = "NA"
            g_score = "NA"
            g_content_comment = "NA"
            t = "NA"
            # lấy thông tin đưa vào các biến
            # LẤY THÔNG TIN CỦA CÁC COMMENT
            try:
                comments= driver.find_elements_by_xpath('//div[@class="review_top review_top_l"]')
                num_comment_items= min(len(comments),100)
            except:
                item= Bigdata2Item()
                item['g_url']= g_url
                item['g_reviewer_name'] = g_reviewer_name
                item['g_comment_date'] = g_comment_date
                # item['g_reviever_helpfulvote'] = g_reviever_helpfulvote
                item['g_score'] = g_score
                item['g_content_comment'] = g_content_comment
                yield item            
            #Duyệt tất cả các comments => đưa giá trị vào các biến
            try:
                expand = driver.find_elements_by_xpath('//span[@class="toggle_expand_collapse toggle_expand"]')
                for i in expand:
                    i.click()
            except:
                item= Bigdata2Item()
                item['g_url']= g_url
                item['g_reviewer_name'] = g_reviewer_name
                item['g_comment_date'] = g_comment_date
                # item['g_reviever_helpfulvote'] = g_reviever_helpfulvote
                item['g_score'] = g_score
                item['g_content_comment'] = g_content_comment
                yield item
            for j in range(num_comment_items):
                try:
                    g_reviewer_name= comments[j].find_element_by_xpath('.//div[@class="name"]/a').text
                except:
                    g_reviewer_name = "NA"
                try:
                    g_comment_date = comments[j].find_element_by_xpath('.//div[@class="date"]').text
                except:
                    g_comment_date = "NA"
                try:
                    g_score = comments[j].find_element_by_xpath('.//div[@class="review_grade"]/div').text
                except:
                    g_score = "NA"
                try:
                    g_content_comment = comments[j].find_element_by_xpath('.//div[@class="review_body"]/span').text
                    # g_content_comment = comments[j].find_element_by_xpath('.//span[@class="blurb blurb_expanded"]').text
                except:
                    g_content_comment = "NA"
                item= Bigdata2Item()
                item['g_url']= g_url
                item['g_reviewer_name'] = g_reviewer_name
                item['g_comment_date'] = g_comment_date
                item['g_score'] = g_score
                # item['g_reviever_helpfulvote'] = g_reviever_helpfulvote
                item['g_content_comment'] = g_content_comment
                yield item
            #Nhấn nút tiếp theo
            try:
                #class="ui_button nav next primary
                driver.find_element_by_xpath('//span[@class="flipper next"]/a[@class="action"]').click()
                time.sleep(3)
            except:
                break
        #khi việc crawl hoàn tất
        driver.quit()
        
         
        pass